name: CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  lint:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v3
    
    - name: Setup Node.js
      uses: actions/setup-node@v3
      with:
        node-version: '18'
        cache: 'npm'
        
    - name: Install dependencies
      run: npm ci
        
    - name: Run ESLint
      run: npm run lint || true
      
  build:
    runs-on: ubuntu-latest
    needs: lint
    
    steps:
    - uses: actions/checkout@v3
    
    - name: Setup Node.js
      uses: actions/setup-node@v3
      with:
        node-version: '18'
        cache: 'npm'
        
    - name: Install dependencies
      run: npm ci
        
    - name: Build project
      run: npm run build
      env:
        # Set placeholder values for environment variables required by the build
        NEXT_PUBLIC_RPC_URL: https://data-seed-prebsc-1-s1.binance.org:8545/
        NEXT_PUBLIC_BSC_TESTNET_CHAIN_ID: 97
        NEXT_PUBLIC_VAI_TOKEN_ADDRESS: 0x0000000000000000000000000000000000000000
        NEXT_PUBLIC_FIELD_MANAGER_ADDRESS: 0x0000000000000000000000000000000000000000
        NEXT_PUBLIC_PROPOSAL_MANAGER_ADDRESS: 0x0000000000000000000000000000000000000000
        NEXT_PUBLIC_REFERRAL_MANAGER_ADDRESS: 0x0000000000000000000000000000000000000000
        NEXT_PUBLIC_BOOTSTRAP_BAY_ADDRESS: 0x0000000000000000000000000000000000000000
        NEXTAUTH_SECRET: placeholder-nextauth-secret-key
        NEXTAUTH_URL: http://localhost:3000